# Generated by Django 2.2.4 on 2020-07-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_shirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_shirts',
            field=models.ManyToManyField(related_name='users_who_liked', to='user_app.Shirt'),
        ),
    ]
